### PR TITLE
Nip5 improvements

### PR DESCRIPTION
**Pull request by motorina0**

### CODE REVIEW

**Comment by bitkarrot** [comment]
I don't want to be super annoying about NIP-05s but if we have NIP-05 as an option, the preferred relays should also be able to be added. It just makes it less taxing on resources, if nostr clients have a list of preferred relays,  instead of trying to poll every large relay to look for user data. Also it can be difficult to locate new users if they aren't actively posting to large relays.

(these are just some things I've noticed while building on nostr recently)

**Comment by bitkarrot** [comment]
[I am also OK if you want to assign to me preferred relays stuff]

**Comment by motorina0** [comment]
> [I am also OK if you want to assign to me preferred relays stuff]

This is implemented on the last `nostrnip5` extension.

**Comment by motorina0** [comment]
deprecated by https://github.com/lnbits/lnurlp/pull/60

**Pull request closed without merging**
